[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.133"
chrono = "0.4.38"
rocket = "0.5.1"
rusqlite = "0.32.1"
minio = "0.1.0"
rand = "0.8.5"
hex = "0.4.3"
tokio = "1.42.0"
bcrypt = "0.16.0"
